### PR TITLE
Fix grammar for search command result

### LINKED ISSUE #416: Search command message grammar issue
image

When only 1 person is listed it prints 1 personS listed.

### PR DESCRIPTION
**Pull request by Justin-Yeo**
- If the number of person returned in the result is less than or equals to 1, it would be 'person'
- If the number  is 2 or greater, it would be 'persons'

Fixes #416

### CODE REVIEW

**Comment by voldiemort** [comment]
I vaguely recall seeing something in the CS2103T website which said that even changing the command result message can be considered as violating the feature freeze. Can anyone confirm if this is true? @chongsun2002 @seah-minlong @zzzlou

**Comment by chongsun2002** [comment]
image

Grammar is ok.

**Comment by voldiemort** [comment]
👌

**Review by voldiemort — APPROVED** [review]
LGTM but do get the CI errors fixed before merging

**Review by seah-minlong — CHANGES_REQUESTED** [review]
image

**Pull request closed without merging**
